project:
  type: website
  output-dir: docs


website:
  title: "Benjamin Frizzell's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bfrizzell01/
      - icon: linkedin
        href: https://www.linkedin.com/in/benjamin-frizzell-843436309/
     
format:
  html:
    theme: cosmo
    css: styles.css



